services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - "../mysql/conf:/etc/mysql/conf.d"
      - "../mysql/data:/var/lib/mysql"
      - "../mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - dickseek-net
  dickseekService:
    build:
      context: .
      dockerfile: dickseek.dockerfile
    container_name: dickseek-service
    image: dickseek-service:latest 
    ports:
      - "8080:8080"
    networks:
      - dickseek-net
    depends_on:
      - mysql
  nginx:
    image: nginx
    container_name: dickseek-nginx
    ports:
      - "18080:18080"
    networks:
      - dickseek-net
    volumes:
      - "./nginx_dickseek/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx_dickseek/html:/usr/share/nginx/html"
    depends_on:
      - dickseekService

networks:
  dickseek-net:
     name: dickseek-net